const STAGES = {idea:'기획',script:'대본 준비',production:'제작 중',review:'검수',scheduled:'예약 게시',published:'게시 완료',hold:'보류',archived:'보관'};
const PLATFORMS = ['YouTube','Instagram','TikTok','Blog','Website','Other'];
const AUDIENCES = {unknown:'미확인',general:'일반',kids:'아동용'};
const esc = (s='') => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(value) { try { const u=new URL(value); return ['https:','http:'].includes(u.protocol) && !u.username && !u.password ? u.href : ''; } catch { return ''; } }
const link = (url,label) => safeUrl(url) ? `<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>` : '';
const number = n => n == null ? '—' : Number(n).toLocaleString('ko-KR');
const date = s => s && Number.isFinite(Date.parse(s)) ? new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(s)) : '미확인';
const localDate = s => { const d=s ? new Date(s) : new Date(); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); };
const options = (obj,value='') => Object.entries(obj).map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('');
export function latestMetrics(rows) { const map=new Map(); for(const r of rows) if(!map.has(r.item_id) || Date.parse(r.observed_at)>Date.parse(map.get(r.item_id).observed_at)) map.set(r.item_id,r); return map; }
export function metricDelta(rows,itemId,key) { const valid=rows.filter(r=>r.item_id===itemId && r[key]!=null).sort((a,b)=>Date.parse(b.observed_at)-Date.parse(a.observed_at)); if(valid.length<2)return null; return Number(valid[0][key])-Number(valid[1][key]); }

export function createContentOperations(db,getUser) {
  const root=document.querySelector('#content-section');
  let channels=[],items=[],metrics=[],resources=[],loaded=false,generation=0,saving=false;
  root.innerHTML=`<div class="co-hero"><div><p class="eyebrow">CONTENT COMMAND CENTER</p><h2>콘텐츠가 성과로 이어지는 곳</h2><p>브랜드별 제작부터 게시, 시청 반응까지 한눈에.</p></div><div class="co-toolbar"><button class="secondary" data-co="refresh">↻ 현황 새로고침</button><button class="primary" data-co="item">+ 콘텐츠</button></div></div>
    <p id="co-message" class="form-message co-message" role="status" aria-live="polite"></p>
    <div class="co-filters"><label>브랜드<select id="co-brand"><option value="">전체 브랜드</option></select></label><label>채널<select id="co-channel"><option value="">전체 채널</option></select></label><label>단계<select id="co-stage"><option value="">전체 단계</option>${options(STAGES)}</select></label><label>검색<input id="co-search" type="search" placeholder="제목 · 시리즈 · 다음 할 일"></label></div>
    <div id="co-summary" class="summary-grid"></div>
    <div class="co-dashboard-grid"><section class="panel co-chart-panel"><div class="panel-head"><div><p class="eyebrow">PRODUCTION MIX</p><h2>제작 파이프라인</h2></div></div><div id="co-pipeline"></div></section><section class="panel co-chart-panel"><div class="panel-head"><div><p class="eyebrow">CONTENT PERFORMANCE</p><h2>콘텐츠별 조회수</h2></div><span class="panel-note">최근 확인한 누적 수치</span></div><div id="co-performance"></div></section></div>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">NEXT UP</p><h2>다음으로 진행할 콘텐츠</h2></div><span class="panel-note">카드를 눌러 진행 상태 편집</span></div><div id="co-next" class="co-next-grid"></div></section>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">BRANDS & CHANNELS</p><h2>운영 채널</h2></div><button class="secondary" data-co="channel">+ 브랜드·채널</button></div><div id="co-channels" class="co-channels"></div></section>
    <details class="panel co-details"><summary>콘텐츠 상세 내역 <span>실적 기록 · 링크 · CSV</span></summary><div class="co-toolbar"><button class="secondary" data-co="export">CSV 내보내기</button></div><div class="asset-table-wrap"><table class="asset-table"><thead><tr><th>콘텐츠 · 채널</th><th>단계 · 일정</th><th>다음 할 일 · 장애</th><th>최근 실적</th><th>앱 · 전환 링크</th></tr></thead><tbody id="co-rows"></tbody></table></div></details>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">RESOURCES</p><h2>제작 자원 · 연결 상태</h2></div></div><div id="co-resources" class="co-resources"></div><p class="panel-note">실적·잔액은 표시된 확인 시점 기준입니다. YouTube 자동 수집은 연결 전이며 새로고침은 저장된 기록을 불러옵니다.</p></section>`;
  const dialog=document.createElement('dialog'); dialog.className='co-dialog'; dialog.setAttribute('aria-label','콘텐츠 운영 편집'); document.body.append(dialog);
  const $=s=>root.querySelector(s), field=n=>dialog.querySelector(`[name="${n}"]`);
  const setMessage=s=>{$('#co-message').textContent=s;};
  async function readAll(table,order) { const out=[]; for(let offset=0;;offset+=500){const {data,error}=await db.from(table).select('*').order(order).order('id').range(offset,offset+499);if(error)throw error;out.push(...data);if(data.length<500)return out;} }
  async function load(force=false){
    if(!getUser())return false; if(loaded&&!force){render();return true;} const token=++generation;setMessage('콘텐츠 현황을 불러오는 중…');
    try{const result=await Promise.all([readAll('admin_media_channels','created_at'),readAll('admin_media_items','created_at'),readAll('admin_media_metrics','observed_at'),readAll('admin_media_resources','name')]);if(token!==generation||!getUser())return false;[channels,items,metrics,resources]=result;loaded=true;render();setMessage('저장된 현황을 불러왔습니다. 실적 확인 시점은 각 기록을 참고하세요.');return true;}
    catch{if(token===generation)setMessage('현황을 불러오지 못했습니다. 로그인과 연결 상태를 확인한 후 새로고침하세요.');return false;}
  }
  function clear(){generation++;channels=[];items=[];metrics=[];resources=[];loaded=false;dialog.close();dialog.innerHTML='';for(const s of ['#co-summary','#co-channels','#co-rows','#co-resources','#co-pipeline','#co-performance','#co-next'])$(s).innerHTML='';$('#co-brand').innerHTML='<option value="">전체 브랜드</option>';$('#co-channel').innerHTML='<option value="">전체 채널</option>';$('#co-stage').value='';$('#co-search').value='';setMessage('');}
  function channel(id){return channels.find(c=>c.id===id)||{};}
  function filtered(){const brand=$('#co-brand').value,ch=$('#co-channel').value,stage=$('#co-stage').value,q=$('#co-search').value.trim().toLowerCase();return items.filter(i=>(!brand||channel(i.channel_id).brand===brand)&&(!ch||i.channel_id===ch)&&(stage?i.stage===stage:i.stage!=='archived')&&[i.title,i.series,i.next_action,i.blocker,channel(i.channel_id).brand].join(' ').toLowerCase().includes(q));}
  function fillFilters(){for(const [id,obj,label] of [['#co-brand',Object.fromEntries(channels.map(c=>[c.brand,c.brand])),'전체 브랜드'],['#co-channel',Object.fromEntries(channels.map(c=>[c.id,`${c.name} · ${c.platform}`])),'전체 채널']]){const old=$(id).value;$(id).innerHTML=`<option value="">${label}</option>${options(obj,old)}`;}}
  function render(){fillFilters();const rows=filtered(),recent=latestMetrics(metrics),published=rows.filter(i=>i.stage==='published');
    const measured=published.map(i=>({item:i,metric:recent.get(i.id)})).filter(x=>x.metric?.views!=null);
    const pending=rows.filter(i=>!['published','archived'].includes(i.stage));
    const blocked=rows.filter(i=>i.blocker||i.stage==='hold');
    const totalViews=measured.length?measured.reduce((n,x)=>n+Number(x.metric.views),0):null;
    const times=measured.map(x=>Date.parse(x.metric.observed_at)).filter(Number.isFinite);
    const freshness=times.length?date(new Date(Math.min(...times)).toISOString()):'확인 대기';
    $('#co-summary').innerHTML=[['게시 완료',published.length,`등록 콘텐츠 ${rows.length}개 중`,'green','▶'],['제작 대기·진행',pending.length,'기획부터 게시 전까지','blue','◷'],['확인된 누적 조회',totalViews,`${measured.length}/${published.length}개 확인 · 미확인 제외`,'purple','↗'],['확인할 장애',blocked.length,blocked.length?'진행이 막힌 콘텐츠':'등록된 장애 없음','amber','!']].map(([l,n,d,c,icon])=>`<article class="summary-card co-kpi ${c}"><span class="co-kpi-icon" aria-hidden="true">${icon}</span><span>${l}</span><b>${number(n)}</b><small>${d}</small></article>`).join('');
    const colors={idea:'#a5b4fc',script:'#818cf8',production:'#4665ed',review:'#9b6cdb',scheduled:'#31a6b0',published:'#219c78',hold:'#e29a38',archived:'#98a2b3'};
    let offset=0; const activeStages=Object.entries(STAGES).map(([k,l])=>({k,l,n:rows.filter(i=>i.stage===k).length})).filter(x=>x.n);
    const arcs=activeStages.map(x=>{const n=x.n/Math.max(rows.length,1)*100;const arc=`<circle cx="100" cy="100" r="78" fill="none" stroke="${colors[x.k]}" stroke-width="22" pathLength="100" stroke-dasharray="${n} ${100-n}" stroke-dashoffset="${-offset}" transform="rotate(-90 100 100)"/>`;offset+=n;return arc;}).join('');
    $('#co-pipeline').innerHTML=`<div class="co-mix"><svg viewBox="0 0 200 200" role="img" aria-label="${esc(activeStages.map(x=>`${x.l} ${x.n}개`).join(', ')||'등록 콘텐츠 없음')}"><circle cx="100" cy="100" r="78" fill="none" stroke="#eef1f7" stroke-width="22"/>${arcs}<text x="100" y="100" text-anchor="middle" class="co-donut-count">${rows.length}</text><text x="100" y="125" text-anchor="middle" class="co-donut-label">전체 콘텐츠</text></svg><div class="co-legend">${Object.entries(STAGES).filter(([k])=>k!=='archived'||rows.some(i=>i.stage===k)).map(([k,l])=>`<button data-co="stage-filter" data-stage="${k}"><span class="co-dot" style="background:${colors[k]}"></span><span>${l}</span><b>${rows.filter(i=>i.stage===k).length}</b></button>`).join('')}</div></div>`;
    const ranked=[...measured].sort((a,b)=>Number(b.metric.views)-Number(a.metric.views)).slice(0,6),max=Math.max(1,...ranked.map(x=>Number(x.metric.views)));
    $('#co-performance').innerHTML=ranked.length?`<div class="co-rank-list">${ranked.map(({item:i,metric:m})=>`<button class="co-rank" data-co="metric" data-id="${esc(i.id)}"><span class="co-rank-label">${esc(i.title)}<small>${esc(channel(i.channel_id).name)}</small></span><span class="co-bar-track"><span style="width:${Number(m.views)/max*100}%"></span></span><b>${number(m.views)}</b></button>`).join('')}</div><p class="co-chart-note">${freshness} 이후 확인 · 콘텐츠별 관측 시각은 상세 내역 참고</p>`:'<div class="co-chart-empty"><b>아직 확인한 조회수가 없습니다</b><span>게시 콘텐츠의 실적을 기록하면 차트가 표시됩니다.</span></div>';
    const ordered=[...pending].sort((a,b)=>Number(!!b.blocker)-Number(!!a.blocker)||(a.target_date||'9999').localeCompare(b.target_date||'9999'));
    $('#co-next').innerHTML=ordered.slice(0,6).map(i=>`<button class="co-next-card" data-co="item" data-id="${esc(i.id)}"><div class="co-next-meta"><span class="co-stage" data-stage="${esc(i.stage)}">${STAGES[i.stage]}</span><span>${esc(channel(i.channel_id).platform)}</span></div><h3>${esc(i.title)}</h3><span class="co-small">${esc(channel(i.channel_id).brand)} · ${esc(i.series)||'시리즈 미지정'}</span><p>${esc(i.blocker||i.next_action)||'다음 할 일을 입력하세요.'}</p><footer>${i.blocker?'⚑ 장애 확인':i.target_date?`목표 ${esc(i.target_date)}`:'게시일 미정'}<span>상세 보기 →</span></footer></button>`).join('')||'<p class="co-empty">제작 대기 중인 콘텐츠가 없습니다.</p>';
    $('#co-channels').innerHTML=channels.map(c=>`<article class="co-channel"><span class="co-stage">${esc(c.brand)} · ${esc(c.platform)}</span><h3>${esc(c.name)}${c.archived?' · 보관':''}</h3><p>${esc(c.check_status)}<span class="co-small">최근 점검 ${date(c.checked_at)}</span></p><p>${esc(c.notes)}</p><footer><div class="co-links">${link(c.channel_url,'채널')}${link(c.studio_url,'Studio')}${link(c.app_url,'앱')}</div><button class="secondary" data-co="channel" data-id="${esc(c.id)}">편집</button></footer></article>`).join('')||'<p class="co-empty">첫 브랜드와 채널을 등록하세요.</p>';
    $('#co-rows').innerHTML=rows.map(i=>{const c=channel(i.channel_id),m=recent.get(i.id),delta=metricDelta(metrics,i.id,'views');return `<tr><td class="co-cell"><button class="co-title" data-co="item" data-id="${esc(i.id)}">${esc(i.title)}</button><span class="co-small">${esc(c.brand)} / ${esc(c.name)} · ${esc(c.platform)}<br>${esc(i.series)}</span><div class="co-links">${link(i.published_url,'게시 영상')}${link(i.source_url,'제작 자료')}</div></td><td><span class="co-stage" data-stage="${esc(i.stage)}">${STAGES[i.stage]||'미확인'}</span><span class="co-small">${i.target_date?'목표 '+esc(i.target_date):'목표일 미정'}<br>${AUDIENCES[i.audience]}${i.audience==='kids'?'<br>댓글·알림 사용 제한':''}</span></td><td class="co-cell">${esc(i.next_action)||'—'}${i.blocker?`<p class="co-blocker">${esc(i.blocker)}</p>`:''}</td><td>${m?`<b class="num">조회 ${number(m.views)}</b><span class="co-small">좋아요 ${number(m.likes)} · 댓글 ${i.audience==='kids'&&m.comments==null?'사용 제한':number(m.comments)}<br>${delta==null?'':`이전 기록 대비 ${delta>=0?'+':''}${number(delta)}<br>`}${date(m.observed_at)}<br>${esc(m.source)}</span>`:'<span class="co-small">실적 확인 대기</span>'}<button class="secondary" data-co="metric" data-id="${esc(i.id)}">실적 기록</button></td><td><div class="co-links">${link(i.cta_url,'전환 링크')}</div><span class="co-small">${esc(i.cta_placement)||'위치 미등록'}</span></td></tr>`;}).join('')||'<tr><td colspan="5" class="co-empty">조건에 맞는 콘텐츠가 없습니다.</td></tr>';
    $('#co-resources').innerHTML=resources.map(r=>`<article class="co-resource"><p class="eyebrow">${esc(r.name)}</p><strong>${r.balance==null?'':`${number(r.balance)} ${esc(r.unit)} · `}${esc(r.status)}</strong><p>${esc(r.detail)}</p><span class="co-small">확인 ${date(r.checked_at)}</span><div class="co-links">${link(r.url,'서비스 열기')}</div><button class="secondary" data-co="resource" data-id="${esc(r.id)}">상태 갱신</button></article>`).join('')||'<p class="co-empty">등록된 제작 자원이 없습니다.</p>';
  }
  function input(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
  function area(label,name,value='',rows=3){return `<label class="span-2">${label}<textarea name="${name}" rows="${rows}" maxlength="30000">${esc(value)}</textarea></label>`;}
  function select(label,name,obj,value){return `<label>${label}<select name="${name}">${options(obj,value)}</select></label>`;}
  function open(kind,id){if(!getUser()||saving)return;let row={},body='',heading='';
    if(kind==='channel'){row=channels.find(c=>c.id===id)||{};heading=id?'브랜드·채널 편집':'브랜드·채널 추가';body=input('브랜드','brand',row.brand,'text','required maxlength="120"')+input('채널명','name',row.name,'text','required maxlength="120"')+select('플랫폼','platform',Object.fromEntries(PLATFORMS.map(p=>[p,p])),row.platform||'YouTube')+input('채널 주소','channel_url',row.channel_url,'url')+input('관리 도구 · Studio 주소','studio_url',row.studio_url,'url')+input('앱 · 서비스 주소','app_url',row.app_url,'url')+input('점검 상태','check_status',row.check_status||'미확인')+input('점검 시각 (기기 시간대)','checked_at',row.checked_at?localDate(row.checked_at):'','datetime-local')+area('운영 메모','notes',row.notes)+`<label class="co-check"><input name="archived" type="checkbox" ${row.archived?'checked':''}>채널 보관</label>`;}
    if(kind==='item'){if(!channels.length){setMessage('먼저 브랜드·채널을 추가하세요.');return;}row=items.find(i=>i.id===id)||{};heading=id?'콘텐츠 편집':'콘텐츠 추가';body=select('브랜드 · 채널','channel_id',Object.fromEntries(channels.map(c=>[c.id,`${c.brand} / ${c.name} · ${c.platform}`])),row.channel_id)+input('시리즈 · 캠페인','series',row.series)+input('콘텐츠 제목','title',row.title,'text','required maxlength="250"')+select('제작 단계','stage',STAGES,row.stage||'idea')+input('목표 게시일','target_date',row.target_date,'date')+select('시청 대상','audience',AUDIENCES,row.audience||'unknown')+input('게시 주소','published_url',row.published_url,'url')+input('게시 시각 (기기 시간대)','published_at',row.published_at?localDate(row.published_at):'','datetime-local')+input('원본 · 제작 자료 주소','source_url',row.source_url,'url')+input('앱 · 전환 링크','cta_url',row.cta_url||channel(row.channel_id).app_url,'url')+input('링크 배치 위치','cta_placement',row.cta_placement)+input('다음 할 일','next_action',row.next_action)+area('막힌 점','blocker',row.blocker,2)+area('제작 · 게시 메모','notes',row.notes)+area('대본 · 구성안','script',row.script,7);}
    if(kind==='metric'){row=items.find(i=>i.id===id);if(!row)return;heading='실적 기록 · '+row.title;body='<p class="panel-note span-2">실제로 확인한 누적 수치만 입력하세요. 모르는 값은 비워 두고, 0은 실제 0일 때만 입력합니다. 저장된 기록은 새 기록을 추가해 갱신합니다.</p>'+input('관측 시각 (기기 시간대)','observed_at',localDate(),'datetime-local','required')+input('출처','source',channel(row.channel_id).platform==='YouTube'?'YouTube Studio 수동 확인':'플랫폼 수동 확인','text','required maxlength="200"')+['views','likes','comments','watch_hours','ctr'].map((k,n)=>input(['누적 조회수','누적 좋아요','누적 댓글 수','누적 시청 시간 (시간)','노출 클릭률 (%)'][n],k,'','number',`min="0" step="${n<3?'1':'0.01'}" ${k==='ctr'?'max="100"':''}`)).join('')+area('반응 · 개선 메모','notes','',3)+`<div class="co-history span-2"><b>최근 기록</b>${metrics.filter(m=>m.item_id===id).sort((a,b)=>Date.parse(b.observed_at)-Date.parse(a.observed_at)).slice(0,8).map(m=>`<p>${date(m.observed_at)} · 조회 ${number(m.views)} · 좋아요 ${number(m.likes)} · ${esc(m.source)}<br>${esc(m.notes)}</p>`).join('')||'<p>아직 기록이 없습니다.</p>'}</div>`;}
    if(kind==='resource'){row=resources.find(r=>r.id===id);if(!row)return;heading=row.name+' 상태 갱신';body=input('잔액 (확인하지 못하면 비워 두기)','balance',row.balance,'number','min="0" step="0.01"')+input('단위','unit',row.unit)+input('현재 상태','status',row.status,'text','required')+input('확인 시각 (기기 시간대)','checked_at',row.checked_at?localDate(row.checked_at):'','datetime-local')+input('서비스 주소','url',row.url,'url')+area('상태 설명','detail',row.detail);}
    dialog.innerHTML=`<form><div class="dialog-head"><h2>${esc(heading)}</h2><button type="button" class="icon-button" data-close aria-label="닫기">×</button></div><div class="form-grid">${body}</div><p class="form-message" role="alert" id="co-form-message"></p><div class="dialog-actions"><span></span><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">저장</button></div></form>`;
    dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.querySelector('form').onsubmit=e=>save(e,kind,row);dialog.showModal();
  }
  async function save(event,kind,row){event.preventDefault();if(saving||!getUser())return;const message=dialog.querySelector('#co-form-message'),form=event.currentTarget;const data=Object.fromEntries(new FormData(form));message.textContent='';
    for(const key of Object.keys(data)) if(key.endsWith('_url')||key==='url'){if(data[key]&&!safeUrl(data[key])){message.textContent='주소는 http 또는 https 형식으로 입력하세요.';return;}data[key]=data[key]||null;}
    for(const key of ['checked_at','published_at','observed_at'])if(key in data){if(data[key]&&!Number.isFinite(Date.parse(data[key]))){message.textContent='시각을 확인하세요.';return;}data[key]=data[key]?new Date(data[key]).toISOString():null;}
    if(kind==='item'){data.title=data.title.trim();data.target_date=data.target_date||null;if(!data.title){message.textContent='제목을 입력하세요.';return;}if(data.stage==='published'&&!data.published_url){message.textContent='게시 완료에는 게시 주소가 필요합니다.';return;}}
    if(kind==='channel'){data.brand=data.brand.trim();data.name=data.name.trim();data.archived=field('archived').checked;if(!data.brand||!data.name){message.textContent='브랜드와 채널명을 입력하세요.';return;}}
    if(kind==='metric'){for(const key of ['views','likes','comments','watch_hours','ctr']){data[key]=data[key]===''?null:Number(data[key]);if(data[key]!=null&&(!Number.isFinite(data[key])||data[key]<0||(key==='ctr'&&data[key]>100)||(['views','likes','comments'].includes(key)&&!Number.isSafeInteger(data[key])))){message.textContent='실적 수치를 확인하세요.';return;}}if(['views','likes','comments','watch_hours','ctr'].every(k=>data[k]==null)){message.textContent='확인한 수치를 하나 이상 입력하세요.';return;}if(!data.observed_at||Date.parse(data.observed_at)>Date.now()+60000){message.textContent='관측 시각은 현재 또는 과거여야 합니다.';return;}data.source=data.source.trim();if(!data.source){message.textContent='출처를 입력하세요.';return;}data.item_id=row.id;}
    if(kind==='resource'){data.balance=data.balance===''?null:Number(data.balance);if(data.balance!=null&&(!Number.isFinite(data.balance)||data.balance<0)){message.textContent='잔액을 확인하세요.';return;}}
    if(kind!=='metric')data.updated_at=new Date().toISOString();const table={channel:'admin_media_channels',item:'admin_media_items',metric:'admin_media_metrics',resource:'admin_media_resources'}[kind],token=generation;
    saving=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);
    try{const query=row.id&&kind!=='metric'?db.from(table).update(data).eq('id',row.id):db.from(table).insert(data);const {data:saved,error}=await query.select('id');if(error||!saved?.length)throw error||new Error('No write');if(!getUser()||token!==generation)return;dialog.close();await load(true);setMessage('저장했습니다.');}
    catch{if(getUser()&&token===generation)message.textContent='저장하지 못했습니다. 연결 상태와 입력값을 확인하세요.';}
    finally{saving=false;form.querySelectorAll('button').forEach(b=>b.disabled=false);}
  }
  function exportCsv(){const latest=latestMetrics(metrics),csvCell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const rows=[['브랜드','채널','플랫폼','제목','시리즈','단계','목표일','게시 주소','다음 할 일','막힌 점','조회수','좋아요','댓글','관측 시각','출처'],...filtered().map(i=>{const c=channel(i.channel_id),m=latest.get(i.id)||{};return[c.brand,c.name,c.platform,i.title,i.series,STAGES[i.stage],i.target_date,i.published_url,i.next_action,i.blocker,m.views,m.likes,m.comments,m.observed_at,m.source];})];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='AP-content-status.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  root.addEventListener('click',e=>{const b=e.target.closest('[data-co]');if(!b)return;const k=b.dataset.co;if(k==='stage-filter'){$('#co-stage').value=$('#co-stage').value===b.dataset.stage?'':b.dataset.stage;render();}else if(k==='refresh')load(true);else if(k==='export')exportCsv();else open(k,b.dataset.id);});
  ['#co-brand','#co-channel','#co-stage','#co-search'].forEach(s=>$(s).addEventListener('input',render));
  return {load,clear};
}
