const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createShop(db,getUser){
 const root=document.querySelector('#shop-section');let rows=[],generation=0;
 root.innerHTML='<section class="panel"><h2>Lia Select 상품 관리 · 싱가포르</h2><p>설명·이미지·쇼피 링크를 저장하면 쇼핑몰 새로고침 시 반영됩니다. 결제와 주문은 쇼피에서 관리합니다. 이곳에는 매입가나 고객 정보를 입력하지 마세요.</p><p><a href="https://shop.apholdings.kr/" target="_blank" rel="noopener">쇼핑몰 보기 ↗</a> · <a href="https://seller.shopee.kr/" target="_blank" rel="noopener">쇼피 판매자센터 ↗</a></p><button data-refresh>새로고침</button><p data-message role="status"></p><label>상품<select data-products></select></label><form data-form></form></section>';
 const sel=root.querySelector('[data-products]'),form=root.querySelector('form'),msg=root.querySelector('[data-message]');
 const fields={name:'상품명',size_label:'용량·옵션',description_en:'영문 설명',directions_en:'사용법',cautions_en:'주의사항',image:'이미지 URL',video:'리아 영상 URL'};
 function edit(){let p=rows.find(x=>x.id===sel.value)?.payload;if(!p)return;form.innerHTML=Object.entries(fields).map(([key,label])=>`<label style="display:block;margin:12px 0">${label}<textarea name="${key}" rows="${key==='description_en'?3:2}" style="width:100%">${esc(p[key])}</textarea></label>`).join('')+`<label>싱가포르 쇼피 상품 URL<input name="shopee" type="url" style="width:100%" value="${esc(p.markets.sg.url)}"></label><label>판매 상태<select name="state"><option value="pending">판매 준비 중</option><option value="live" ${p.markets.sg.status==='live'?'selected':''}>판매 중</option></select></label><p><label><input type="checkbox" name="ready"> 판매 중으로 변경할 때 공급·재고·판매 요건·쇼피 상품 등록을 확인했습니다.</label></p><button type="submit">상품 저장</button>`;}
 async function load(){if(!getUser())return;let g=++generation;msg.textContent='불러오는 중…';let {data,error}=await db.from('lia_shop_catalog').select('*').order('id');if(g!==generation||!getUser())return;if(error){msg.textContent='상품을 불러오지 못했습니다.';return;}rows=data;sel.innerHTML=rows.map(x=>`<option value="${esc(x.id)}">${esc(x.payload.brand+' · '+x.payload.name)}</option>`).join('');edit();msg.textContent=rows.length+'개 상품';}
 form.addEventListener('submit',async e=>{e.preventDefault();if(!getUser())return;let p=structuredClone(rows.find(x=>x.id===sel.value).payload),f=new FormData(form),state=f.get('state'),url=String(f.get('shopee')||'').trim();if(state==='live'&&(!/^https:\/\/(?:[a-z0-9-]+\.)?shopee\.sg\//.test(url)||!f.get('ready'))){msg.textContent='판매 확인 체크와 싱가포르 쇼피 상품 링크가 필요합니다.';return;}for(let key of Object.keys(fields)){let v=String(f.get(key)||'').trim();if(['image','video'].includes(key)&&v&&!/^https:\/\//.test(v)&&!/^assets\/[a-zA-Z0-9_.-]+$/.test(v)){msg.textContent='이미지·영상은 HTTPS URL 또는 기존 assets 파일 경로를 사용하세요.';return;}p[key]=v||null;}p.intro.en=p.description_en||'';p.markets.sg={url:url||null,status:state};let button=form.querySelector('button');button.disabled=true;let {error}=await db.from('lia_shop_catalog').update({payload:p,updated_at:new Date().toISOString()}).eq('id',p.id).select('id').single();button.disabled=false;if(error){msg.textContent='저장 실패: 로그인과 권한을 확인하세요.';return;}rows.find(x=>x.id===p.id).payload=p;msg.textContent='저장했습니다. 쇼핑몰에서 새로고침해 확인하세요.';});
 sel.addEventListener('change',edit);root.querySelector('[data-refresh]').addEventListener('click',load);return {load,clear(){generation++;rows=[];sel.innerHTML='';form.innerHTML='';msg.textContent='';}};
}
