const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createShop(db,getUser){
 const root=document.querySelector('#shop-section');let rows=[],generation=0;
 root.innerHTML='<section class="panel"><h2>Lia Select 상품 관리 · 싱가포르</h2><p>설명·이미지·쇼피 링크를 저장하면 쇼핑몰 새로고침 시 반영됩니다. 결제와 주문은 쇼피에서 관리합니다. 이곳에는 매입가나 고객 정보를 입력하지 마세요.</p><p><a href="https://shop.apholdings.kr/" target="_blank" rel="noopener">쇼핑몰 보기 ↗</a> · <a href="https://seller.shopee.kr/" target="_blank" rel="noopener">쇼피 판매자센터 ↗</a></p><button data-refresh>새로고침</button><p data-message role="status"></p><label>상품<select data-products></select></label><form data-form></form></section>';
 const sel=root.querySelector('[data-products]'),form=root.querySelector('form'),msg=root.querySelector('[data-message]');
 const fields={name:'상품명',size_label:'용량·옵션',description_en:'영문 설명',directions_en:'사용법',cautions_en:'주의사항',image:'이미지 URL',video:'리아 영상 URL'};
 function edit(){let p=rows.find(x=>x.id===sel.value)?.payload;if(!p)return;form.innerHTML=Object.entries(fields).map(([key,label])=>`<label style="display:block;margin:12px 0">${label}<textarea name="${key}" rows="${key==='description_en'?3:2}" style="width:100%">${esc(p[key])}</textarea></label>`).join('')+`<label>싱가포르 쇼피 상품 URL<input name="shopee" type="url" style="width:100%" value="${esc(p.markets.sg.url)}"></label><label>판매 상태<select name="state"><option value="pending">판매 준비 중</option><option value="live" ${p.markets.sg.status==='live'?'selected':''}>판매 중</option></select></label><p><label><input type="checkbox" name="ready"> 판매 중으로 변경할 때 공급·재고·판매 요건·쇼피 상품 등록을 확인했습니다.</label></p><button type="submit">상품 저장</button>`;}
 const research=initResearch(root,db,getUser);
 async function load(){if(!getUser())return;let g=++generation;msg.textContent='불러오는 중…';let {data,error}=await db.from('lia_shop_catalog').select('*').order('id');if(g!==generation||!getUser())return;if(error){msg.textContent='상품을 불러오지 못했습니다.';return;}rows=data;sel.innerHTML=rows.map(x=>`<option value="${esc(x.id)}">${esc(x.payload.brand+' · '+x.payload.name)}</option>`).join('');edit();msg.textContent=rows.length+'개 상품';}
 form.addEventListener('submit',async e=>{e.preventDefault();if(!getUser())return;let p=structuredClone(rows.find(x=>x.id===sel.value).payload),f=new FormData(form),state=f.get('state'),url=String(f.get('shopee')||'').trim();if(state==='live'&&(!/^https:\/\/(?:[a-z0-9-]+\.)?shopee\.sg\//.test(url)||!f.get('ready'))){msg.textContent='판매 확인 체크와 싱가포르 쇼피 상품 링크가 필요합니다.';return;}for(let key of Object.keys(fields)){let v=String(f.get(key)||'').trim();if(['image','video'].includes(key)&&v&&!/^https:\/\//.test(v)&&!/^assets\/[a-zA-Z0-9_.-]+$/.test(v)){msg.textContent='이미지·영상은 HTTPS URL 또는 기존 assets 파일 경로를 사용하세요.';return;}p[key]=v||null;}p.intro.en=p.description_en||'';p.markets.sg={url:url||null,status:state};let button=form.querySelector('button');button.disabled=true;let {error}=await db.from('lia_shop_catalog').update({payload:p,updated_at:new Date().toISOString()}).eq('id',p.id).select('id').single();button.disabled=false;if(error){msg.textContent='저장 실패: 로그인과 권한을 확인하세요.';return;}rows.find(x=>x.id===p.id).payload=p;msg.textContent='저장했습니다. 쇼핑몰에서 새로고침해 확인하세요.';});
 sel.addEventListener('change',edit);root.querySelector('[data-refresh]').addEventListener('click',load);return {load,clear(){research.clear();generation++;rows=[];sel.innerHTML='';form.innerHTML='';msg.textContent='';}};
}

function initResearch(root,db,getUser){
 const panel=document.createElement('section');panel.className='panel';panel.hidden=true;
 root.append(panel);
 const catalog=root.firstElementChild,nav=document.createElement('div');nav.style='display:flex;gap:12px;margin-bottom:16px';
 nav.innerHTML='<button type="button" aria-pressed="true">상품 관리</button><button type="button" aria-pressed="false">소싱 조사</button>';
 root.prepend(nav);const [a,b]=nav.children;let generation=0;
 function tab(research){catalog.hidden=research;panel.hidden=!research;a.setAttribute('aria-pressed',String(!research));b.setAttribute('aria-pressed',String(research));}
 a.addEventListener('click',()=>tab(false));b.addEventListener('click',()=>{tab(true);load();});
 const link=(url,label)=>{try{const u=new URL(url);if(u.protocol==='https:'&&!u.username&&!u.password)return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;}catch{}return esc(label);};
 const price=(v,c)=>v==null?'미확인':`${c} ${Number(v).toLocaleString('ko-KR')}`;
 async function load(){if(!getUser())return;const g=++generation;panel.innerHTML='<h2>싱가포르 상품 소싱 조사</h2><p role="status">불러오는 중…</p>';const {data,error}=await db.from('lia_shop_research').select('*').order('id');if(g!==generation||!getUser())return;
 if(error){panel.innerHTML='<h2>소싱 조사</h2><p role="alert">조사 자료를 불러오지 못했습니다. 로그인과 관리자 권한을 확인하세요.</p>';return;}
 const rows=data||[];panel.innerHTML='<h2>싱가포르 상품 소싱 조사</h2><p>관리자 전용 · 고객용 쇼핑몰에 공개되지 않습니다. 목록 표시가, 동일 옵션 비교, 비용 검증을 구분합니다.</p>'+`<p>조사 후보 ${rows.length}개 · 판매 확정 ${rows.filter(r=>r.payload.status==='sale_ready').length}개 · 10만 개 검증 목표 진행 중</p><button type="button" data-research-refresh>조사 새로고침</button><div style="overflow-x:auto"><table style="width:100%;min-width:760px;text-align:left"><thead><tr><th>상품·옵션</th><th>한국 매입 관찰값</th><th>싱가포르 관찰값</th><th>검증 상태·확인일</th><th>근거·다음 확인</th></tr></thead><tbody>${rows.map(({payload:p})=>`<tr><td>${esc(p.name)}<br><small>${esc(p.option||'')}</small></td><td>${price(p.kr_price,'₩')}<br><small>${p.kr_shipping==null?'국내배송 미확인':`배송 ₩ ${Number(p.kr_shipping).toLocaleString('ko-KR')}`}</small></td><td>${price(p.sg_price,'S$')}<br><small>${esc(p.sg_basis||'')}</small></td><td>${esc(p.status_label)}<br>${esc(p.checked_on)}</td><td>${esc(p.note)}<details><summary>출처·비용 가정</summary><p>${(p.sources||[]).map(s=>link(s.url,s.label)).join('<br>')}</p><p>${esc(p.assumptions||'실제 비용 계산 전')}</p></details></td></tr>`).join('')}</tbody></table></div><p>현지 재고 위치·옵션별 최종 결제금액·공급 가능 수량을 확인하기 전에는 가격 경쟁력이 확보된 상품으로 보지 않습니다.</p>`;
 panel.querySelector('[data-research-refresh]').addEventListener('click',load);}
 return {load,clear(){generation++;panel.innerHTML='';tab(false);}};
}
